# Lab 1 Demonstration *Code*

In [1]:
import torch
print("Pytorch version:", torch.__version__)

Pytorch version: 2.6.0+cu124


### Lets talk about Tensors. What are tensors used for?

Create random vectors that have the shape required to answer each of the following questions?

1. How do we represent the predictions of a model that predicts the probability of 20 different classes?
    - What if we want to represent a batch of 5 predictions?
2. Suppose our model takes the values of 10 features to represent the input of a training example. How do we present one training example
    - What if we want to present a batch of 64 examples?
3. How do we represent a greyscale image of size 225 x 225 using a tensor?
    - What if the image is represented using RGB colours instead?
    - What if we want to represent 25 RGB images using a single tensor?

In [ ]:
# tensor to represent the predictions of a model that predicts the probability of 20 different classes
# shape(number of classes)
tensor_predictions = torch.rand(20)

# Add a batch of 5 predictions shape(batch, number of classes)
tensor_predictions = torch.rand(5, 20)

# Represent an element that has 10 features shape(number of features)
tensor_features = torch.rand(10)

# Add a batch of 64 examples shape(batch, number of features)
tensor_batch_features = torch.rand(64, 10)

# Represent a greyscale image of size 225 x 225 using a tensor, shape(width, height)
tensor_gray_scale_image = torch.rand(255, 255)

# Add RGB shape(number of channels, height, width)
tensor_RGB_image = torch.rand(3, 255, 255)

# Add batch of 25 shape(batch, number of channels, height, width)
tensor_batch_RGB_image = torch.rand(25, 3, 255, 255)

# Vectorisation

Why does this matter??

Let's take a look at how we can find the average value in a tensor

In [3]:
import time

In [4]:
# batch, height, width
tensor_x = torch.rand(4, 2, 3)
# tensor_x = torch.rand(40, 20, 30)
# tensor_x = torch.rand(400, 200, 300)
print(tensor_x)
print(tensor_x.shape)

tensor([[[0.7875, 0.3688, 0.1606],
         [0.3923, 0.2122, 0.9450]],

        [[0.2117, 0.6332, 0.6126],
         [0.6502, 0.5407, 0.3543]],

        [[0.1341, 0.8164, 0.5233],
         [0.0438, 0.7431, 0.8307]],

        [[0.3934, 0.9839, 0.6798],
         [0.6460, 0.9043, 0.8303]]])
torch.Size([4, 2, 3])


## The inefficient way (non-vectorised)

In [6]:
# For loops!
start = time.perf_counter()

B, H, W = tensor_x.shape
sum = 0
for i in range(B):
  for j in range(H):
    for k in range(W):
      sum = sum + tensor_x[i, j, k]
avg = sum / (B * H * W)
print(avg)


end = time.perf_counter()
print(f'Elapsed: {end-start:.3f}s')

tensor(0.5583)
Elapsed: 0.073s


## The better way (vectorised!)

In [7]:
start = time.perf_counter()

# compute the mean across the entire vector
avg = tensor_x.mean()
print(avg)
print(tensor_x.shape)

# compute the mean across just the final dimension (dimension 2)
avg = tensor_x.mean(axis=(2,))
print(avg.shape)

end = time.perf_counter()
print(f'Elapsed: {end-start:.3f}s')

tensor(0.5583)
torch.Size([4, 2, 3])
torch.Size([4, 2])
Elapsed: 0.010s


# Reshaping/Permuting

First do some examples of reshape versus permute on the board.

Understanding the difference between reshape and permute. Notice in the example below reshape keeps the order of the elements. Whereas permute modifies the order.


In [8]:
tensor_x = torch.arange(24, dtype=torch.int)
print(tensor_x)

# lets make tensor_x into shape(2, 4, 3) (should we use reshape or permute)?
tensor_x = tensor_x.reshape(2, 4, 3)
print(tensor_x)

# lets combine the last two dimensions (should we use reshape or permute)?
tensor_x = tensor_x.reshape(2, 4*3)
print(tensor_x)

# lets get vector_x back to 1D vector (should we use reshape or permute)?
# notice the order.
tensor_x = tensor_x.reshape(24)
print(tensor_x)

# lets get tensor_x to shape (2, 12) (should we use reshape or permute)?
tensor_x = tensor_x.reshape(2, 12)
print(tensor_x)

# lets switch dimension 0 and dimension 1 (should we use reshape or permute)?
tensor_x = tensor_x.permute(1, 0)
print(tensor_x)

# lets reshape back to 1D
# notice the order
tensor_x = tensor_x.reshape(24)
print(tensor_x)



tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23], dtype=torch.int32)
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]], dtype=torch.int32)
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]], dtype=torch.int32)
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23], dtype=torch.int32)
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]], dtype=torch.int32)
tensor([[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15],
        [ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19],
        [ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]], dtype=torch.int32)
tensor([ 0, 12,  1, 1

### Where is reshape and permute used in practice?

Consider you are given a 4D tensor representing an image of shape(batch, channels, height, width)
1. What if a model requires the tensor representing the image to be in the following shape instead shape(batch, height, width, channels).
2. What if we need to flatten the tensor so that we use a 1D vector to represent each example in the batch? Similar transformations is often need in practice in when training convolutional neural networks.

In [ ]:
# You are given the following tensor for an image
tensor_image = torch.rand(25, 3, 255, 255)

# We use permute to move the channel to the last dimension
tensor_image_modified = tensor_image.permute(0,2,3,1)
print(tensor_image_modified.shape)

# We use reshape to combine the final dimensions to flatten the image
tensor_image_flattened = tensor_image_modified.reshape(25, 3*255*255)
print(tensor_image_flattened.shape)


torch.Size([25, 255, 255, 3])
torch.Size([25, 195075])
